{{- if .Values.broker }}
{{- range $queue, $params := .Values.broker.process.queues }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
  {{- range $key, $value := $.Values.broker.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
    release: {{ $.Release.Name }}
  name: '{{ $.Release.Name }}-broker-{{ $params.name }}-hpa'
spec:
  maxReplicas: {{ $params.maxReplicas }}
  metrics:
  - type: Object
    object:
      metric:
        name: 'rabbitmq_{{ $.Release.Name }}_{{ $queue }}_messages_ready'
      describedObject:
        apiVersion: v1
        kind: Service
        name: prometheus-rabbitmq-exporter
      target:
        type: Value
        value: {{ $params.maxReadyMessagesForHpa }}
  minReplicas: 1
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ $.Release.Name }}-broker-{{ $params.name }}'
---
{{- end }}
{{- end }}
